version: '3.8'

services:
  rag-bot:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - hf_cache:/root/.cache/huggingface
    environment:
      - DB_PATH=vector_db
      - LLM_MODEL=deepseek-v3.1:671b-cloud
      - EMBEDDING_MODEL=BAAI/bge-m3
      - OLLAMA_BASE_URL=http://localhost:11434
    restart: always

volumes:
  hf_cache:
